//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projektzespolowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klienci
    {
        public Klienci()
        {
            this.Wystapienia = new HashSet<Wystapienia>();
        }
    
        public int Klienci_ID { get; set; }
        public string Klient_Imie { get; set; }
        public string Klient_Nazwisko { get; set; }
        public Nullable<decimal> Klient_tel { get; set; }
    
        public virtual ICollection<Wystapienia> Wystapienia { get; set; }
    }
}
