//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projektzespolowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miejsca
    {
        public Miejsca()
        {
            this.Kursy = new HashSet<Kursy>();
        }
    
        public int miejsce_ID { get; set; }
        public string miejsce_typ { get; set; }
        public string miejsce_ulica { get; set; }
    
        public virtual ICollection<Kursy> Kursy { get; set; }
    }
}
