//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projektzespolowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przewodnicy
    {
        public Przewodnicy()
        {
            this.Terminy = new HashSet<Terminy>();
        }
    
        public int przewodnik_ID { get; set; }
        public string przewodnik_Imie { get; set; }
        public string Przewodnik_nazwisko { get; set; }
        public Nullable<decimal> przewodnik_tel { get; set; }
    
        public virtual ICollection<Terminy> Terminy { get; set; }
    }
}
