//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projektzespolowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminy
    {
        public Terminy()
        {
            this.Wystapienia = new HashSet<Wystapienia>();
            this.Przewodnicy = new HashSet<Przewodnicy>();
        }
    
        public int Termin_ID { get; set; }
        public Nullable<int> wycieczka_ID { get; set; }
        public Nullable<System.DateTime> Termin_Data { get; set; }
    
        public virtual wycieczki wycieczki { get; set; }
        public virtual ICollection<Wystapienia> Wystapienia { get; set; }
        public virtual ICollection<Przewodnicy> Przewodnicy { get; set; }
    }
}
