//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projektzespolowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class wycieczki
    {
        public wycieczki()
        {
            this.Kursy = new HashSet<Kursy>();
            this.Terminy = new HashSet<Terminy>();
            this.Wymagania = new HashSet<Wymagania>();
        }
    
        public int wycieczka_ID { get; set; }
        public string wycieczka_nazwa { get; set; }
        public Nullable<decimal> Ilosc_osob { get; set; }
        public string zbiorka_wycieczki { get; set; }
        public Nullable<decimal> Cena { get; set; }
    
        public virtual ICollection<Kursy> Kursy { get; set; }
        public virtual ICollection<Terminy> Terminy { get; set; }
        public virtual ICollection<Wymagania> Wymagania { get; set; }
    }
}
