//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projektzespolowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wystapienia
    {
        public int Wystapienia_ID { get; set; }
        public Nullable<int> Termin_ID { get; set; }
        public Nullable<int> Klienci_ID { get; set; }
        public Nullable<decimal> Oplata_za_wystapienie { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Terminy Terminy { get; set; }
    }
}
